export const CYCLE_PHASES = [
  {
    name:        "Menstruation",
    days:        "Days 1–5",
    emoji:       "🩸",
    color:       "#C8909A",
    bg:          "rgba(200,144,154,0.1)",
    description: "Rest, warmth, gentleness",
    hormone:     "Estrogen & progesterone drop",
    energy:      "Low",
    mood:        "Reflective, introverted",
    bestFor:     "Rest, journaling, warm foods",
    tips:        ["🍵 Warm ginger tea", "🛁 Hot water bottle", "🧘 Child's pose", "💤 Extra sleep"],
  },
  {
    name:        "Follicular",
    days:        "Days 6–13",
    emoji:       "🌱",
    color:       "#9DDDD0",
    bg:          "rgba(157,221,208,0.1)",
    description: "Energy rising, creativity blooms",
    hormone:     "Estrogen rises steadily",
    energy:      "Rising",
    mood:        "Optimistic, motivated",
    bestFor:     "New projects, socialising, cardio",
    tips:        ["🏃 Light cardio", "🥗 Fresh salads", "📚 Learn something", "🌟 Try something new"],
  },
  {
    name:        "Ovulation",
    days:        "Day 14",
    emoji:       "✨",
    color:       "#9B7BB8",
    bg:          "rgba(155,123,184,0.1)",
    description: "Peak energy, peak confidence",
    hormone:     "LH surge, estrogen peaks",
    energy:      "Peak",
    mood:        "Confident, magnetic",
    bestFor:     "Presentations, dates, high-intensity",
    tips:        ["💬 Important talks", "🏋️ Intense workouts", "💃 Social events", "🎯 Set big goals"],
  },
  {
    name:        "Luteal",
    days:        "Days 15–28",
    emoji:       "🍂",
    color:       "#FCDEC0",
    bg:          "rgba(252,222,192,0.25)",
    description: "Slow down, nourish yourself",
    hormone:     "Progesterone rises",
    energy:      "Declining",
    mood:        "Introspective, sensitive",
    bestFor:     "Creative work, gentle exercise",
    tips:        ["🍫 Dark chocolate", "📓 Journaling", "🧘 Gentle yoga", "🌙 Early bedtime"],
  },
];
